// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcUZakZyJbBW8Vbgh9XActohcZellQ8aY',
    appId: '1:450066356671:web:9ef448e8f9dd4157cc290a',
    messagingSenderId: '450066356671',
    projectId: 'bigbasket-88e7a',
    authDomain: 'bigbasket-88e7a.firebaseapp.com',
    storageBucket: 'bigbasket-88e7a.firebasestorage.app',
    measurementId: 'G-DHN1PLJJP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZa0rWGM8bt17Cm1Mh6m3S-bZzekPgP34',
    appId: '1:450066356671:android:ac35b0fd4d77f3c1cc290a',
    messagingSenderId: '450066356671',
    projectId: 'bigbasket-88e7a',
    storageBucket: 'bigbasket-88e7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOg-1lKnmDH_8fvRIAS0z4FrkMbC_w88',
    appId: '1:450066356671:ios:c99d8a06af3f4d0bcc290a',
    messagingSenderId: '450066356671',
    projectId: 'bigbasket-88e7a',
    storageBucket: 'bigbasket-88e7a.firebasestorage.app',
    iosBundleId: 'com.example.bigbasketWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaOg-1lKnmDH_8fvRIAS0z4FrkMbC_w88',
    appId: '1:450066356671:ios:c99d8a06af3f4d0bcc290a',
    messagingSenderId: '450066356671',
    projectId: 'bigbasket-88e7a',
    storageBucket: 'bigbasket-88e7a.firebasestorage.app',
    iosBundleId: 'com.example.bigbasketWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcUZakZyJbBW8Vbgh9XActohcZellQ8aY',
    appId: '1:450066356671:web:1bbb8c284009639ccc290a',
    messagingSenderId: '450066356671',
    projectId: 'bigbasket-88e7a',
    authDomain: 'bigbasket-88e7a.firebaseapp.com',
    storageBucket: 'bigbasket-88e7a.firebasestorage.app',
    measurementId: 'G-KBFZQ2KBZE',
  );
}
